import pathlib
from typing import Union, Tuple
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        self.data_fname = self.fname_validation(data_fname)
        self.data = None

    def fname_validation(self, data_fname):
        """
        Checks whether the given file is valid.

        Parameters
        ----------
        data_fname : pathlib.Path or str
            Path to the data file.

        Returns
        -------
        pathlib.Path
            The validated file path as a pathlib.Path object.

        Raises
        ------
        ValueError
            If the file does not exist.
        """
        # Convert the path to a pathlib object
        data_fname = pathlib.Path(data_fname)

        # Check if Path exists, if not raise an error
        if not data_fname.exists():
            raise ValueError("File does not exist")
        
        # Return the valid path
        return data_fname
    
    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        # Read data from the validated path
        self.data = pd.read_json(self.data_fname)

        # Convert nan strings to nan objects
        self.data = self.data.replace('nan', np.nan)
    
    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """Calculates and plots the age distribution of the participants.

            Returns
            -------
            hist : np.ndarray
                Number of people in a given bin
            bins : np.ndarray
                Bin edges
        """

        # Get age column without nans
        ages = self.data['age'].dropna().astype(int)

        # Get bins and histogram objects
        bins = np.arange(0, 101, 10)
        hist, bins = np.histogram(ages, bins=bins)

        # Plot the histogram
        plt.hist(ages, bins=bins, color='lightblue', edgecolor='black', linewidth=0.7)
        plt.xlabel('Age')
        plt.ylabel('Number of participants')
        plt.show()
        plt.savefig('age_distribution.jpeg') # Save the plot

        return hist, bins
    
    def email_validation(self, email_address):
        """
        Checks whether an email address is valid.

        Parameters
        ----------
        email_address : str
            Email address to validate.

        Returns
        -------
        bool
            True if the email address is valid, False otherwise.
        """

        # Check for missing email address
        if pd.isna(email_address):
            return False
        
        # Ensure the email is a string
        email_address = str(email_address)

        # The email must contain exactly one '@' that is not at the beginning or end
        if email_address.count('@') != 1 or email_address.startswith('@') or email_address.endswith('@'):
            return False
        
        # The email must contain at least one '.' that is not at the beginning or end
        if email_address.count('.') == 0 or email_address.startswith('.') or email_address.endswith('.'):
            return False
        
        # Get the '@' sign index
        at_index = email_address.index('@')

        # The character immediately after '@' cannot be '.'
        if email_address[at_index + 1] == '.':
            return False
        
        # My additions: there must be at least one '.' after the '@'
        if '.' not in email_address[at_index + 1:]:
            return False
        
        return True

    def remove_rows_without_mail(self) -> pd.DataFrame:
        """Checks self.data for rows with invalid emails, and removes them.

        Returns
        -------
        df : pd.DataFrame
        A corrected DataFrame, i.e. the same table but with the erroneous rows removed and
        the (ordinal) index after a reset.
        """
        # Apply the helper function 'email validation' to the email column of the data 
        df = self.data[self.data['email'].apply(self.email_validation)]
        df = df.reset_index(drop=True)

        return df
        
    
    def fill_na_with_mean(self) -> Tuple[pd.DataFrame, np.ndarray]:
        """Finds, in the original DataFrame, the subjects that didn't answer
            all questions, and replaces that missing value with the mean of the
            other grades for that student.

            Returns
            -------
            df : pd.DataFrame
                The corrected DataFrame after insertion of the mean grade
            arr : np.ndarray
                Row indices of the students that their new grades were generated
        """

        # Init question columns name and an empty list for the corrected indices
        question_cols = ['q1', 'q2', 'q3', 'q4', 'q5']
        corrected = []

        for i in self.data.index:
            q_res = self.data.loc[i, question_cols]

            if q_res.isna().any():
                corrected.append(i)
                mean = q_res.mean()

                # Fill null questions with the mean of all other questions
                self.data.loc[i, question_cols] = q_res.fillna(mean)

        return self.data, np.array(corrected)

    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:
        """Calculates the average score of a subject and adds a new "score" column
        with it.

        If the subject has more than "maximal_nans_per_sub" NaN in his grades, the
        score should be NA. Otherwise, the score is simply the mean of the other grades.
        The datatype of score is UInt8, and the floating point raw numbers should be
        rounded down.

        Parameters
        ----------
        maximal_nans_per_sub : int, optional
            Number of allowed NaNs per subject before giving a NA score.

        Returns
        -------
        pd.DataFrame
            A new DF with a new column - "score".
        """

        # Init question columns name and an empty list to store the scores
        question_cols = ['q1', 'q2', 'q3', 'q4', 'q5']
        scores = []

        for i in self.data.index:
            q_res = self.data.loc[i, question_cols]

            if q_res.isna().sum() > maximal_nans_per_sub:
                # Score should be nan
                scores.append(pd.NA)

            else:
                # Score should be mean of other questions rounded down
                score = np.floor(q_res.mean())
                scores.append(score)

        # Create the new column
        self.data['score'] = pd.Series(scores, dtype='UInt8')

        return self.data
    
    def correlate_gender_age(self) -> pd.DataFrame:
        """Looks for a correlation between the gender of the subject, their age
            and the score for all five questions.

        Returns
        -------
        pd.DataFrame
            A DataFrame with a MultiIndex containing the gender and whether the subject is above
            40 years of age, and the average score in each of the five questions.
        """

        # Init question columns name 
        question_cols = ['q1', 'q2', 'q3', 'q4', 'q5']

        # Drop rows without age
        self.data = self.data[self.data['age'].notna()]

        # Transform the df index into a multi-index
        self.data.index = pd.MultiIndex.from_arrays(
            [self.data.index, self.data['gender'], self.data['age']],
            names=['index', 'gender', 'age'])

        # Compute the mean for each qustion by gender and age
        grouped = self.data.groupby([self.data['gender'], self.data['age'] > 40])[question_cols].mean()
        grouped.index.names = ['gender', 'age']

        return grouped
    


def main(path):
    qa_object = QuestionnaireAnalysis(path)
    qa_object.read_data()

    q1 = qa_object.show_age_distrib()
    q2 = qa_object.remove_rows_without_mail()
    q3 = qa_object.fill_na_with_mean()
    q4 = qa_object.score_subjects()
    q5 = qa_object.correlate_gender_age()

    return (q1, q2, q3, q4, q5)


if __name__ == '__main__':
    path = 'data.json'
    return_vals = main(path)

    # Print the results
    for i in range(5):
        print(f'Question {i+1} solution: {return_vals[i]}')